# Generated by Django 3.1.12 on 2025-02-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
