# Generated by Django 4.2.19 on 2025-02-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20250223_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
